language: node_js
node_js:
  - lts/*
addons:
  apt:
    packages:
      - libgconf-2-4
      - libsecret-1-dev
cache:
  npm: true
  directories:
    # folder with Cypress binary
    - ~/.cache
jobs:
  include:
    - stage: Unit Tests
      if: env(TEST_TYPE) != "e2e"
      script: npm test
    - stage: Integration Tests
      if: env(TEST_TYPE) = "e2e"
      script: npm run test:cypress
