language: node_js
node_js:
  - lts/*
addons:
  apt:
    packages:
      - libgconf-2-4
      - libsecret-1-dev
cache:
  npm: true
  directories:
    # folder with Cypress binary
    - ~/.cache
jobs:
  include:
    - stage: Local Tests
      if: env(TEST_TARGET) IS blank
      env: NODE_ENV=development
      script: npm test
#    - stage: Live Tests
#      if: env(TEST_TARGET) IS present
#      before_script: echo "running E2E tests against $TEST_TARGET at $CYPRESS_baseUrl"
#      script: npm run test:cypress
    - stage: Build & Deploy
      if: env(NODE_ENV) = production
      env: NODE_ENV=production
      script: npm run export
      deploy:
        provider: netlify
        site: $NETLIFY_SITE
        auth: $NETLIFY_AUTH
        edge: true # opt in to dpl v2
        dir: "__sapper__/export"
        on:
          branch: next/major
