language: node_js
node_js:
  - lts/*
addons:
  apt:
    packages:
      - libgconf-2-4
      - libsecret-1-dev
cache:
  npm: true
  directories:
    # folder with Cypress binary
    - ~/.cache
jobs:
  include:
    - stage: test
      script: npm test
    - stage: build
      script: npm run build && npm run export
    - stage: deploy
      script: skip
      deploy:
        provider: netlify
        site: $NETLIFY_SITE
        auth: $NETLIFY_AUTH
        edge: true # opt in to dpl v2
        dir: "__sapper__/build/"
        on:
          branch: dev
