language: node_js
node_js:
  - lts/*
addons:
  apt:
    packages:
      - libgconf-2-4
      - libsecret-1-dev
cache:
  npm: true
  directories:
    # folder with Cypress binary
    - ~/.cache
deploy:
  provider: netlify
  site: $NETLIFY_SITE
  auth: $NETLIFY_AUTH
  edge: true # opt in to dpl v2
  local_dir: "__sapper__/build/"
